<?php

/**
 * V0BidRecommendationNormQuery
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ValeryVerkhoturov\WbApiClient\Promotion
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Маркетинг и продвижение
 *
 * Узнать больше о маркетинге и продвижении можно в [справочном центре](https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e)  Методы маркетинга и продвижения позволяют: 1. Получать информацию о кампаниях [продвижения](https://dev.wildberries.ru/openapi/promotion#tag/campaigns) и [медиакампаниях](https://dev.wildberries.ru/openapi/promotion#tag/media) 2. [Создавать](https://dev.wildberries.ru/openapi/promotion#tag/creatingCampaigns) и [управлять](https://dev.wildberries.ru/openapi/promotion#tag/campaignManagement) кампаниями 3. Управлять [финансами](https://dev.wildberries.ru/openapi/promotion#tag/finances) кампаний 4. Выгружать [статистику](https://dev.wildberries.ru/openapi/promotion#tag/statistics) кампаний продвижения и медиакампаний 5. Работать с [календарём акций](https://dev.wildberries.ru/openapi/promotion#tag/promoCalendar) Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  Вы можете протестировать методы продвижения в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/promotion) для управления тестовым балансом
 *
 * The version of the OpenAPI document: promotion
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ValeryVerkhoturov\WbApiClient\Promotion\Model;

use ArrayAccess;
use ValeryVerkhoturov\WbApiClient\Promotion\ObjectSerializer;

/**
 * V0BidRecommendationNormQuery Class Doc Comment
 *
 * @category Class
 * @package  ValeryVerkhoturov\WbApiClient\Promotion
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V0BidRecommendationNormQuery implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'V0BidRecommendationNormQuery';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'norm_query' => 'string',
        'reach_max' => '\ValeryVerkhoturov\WbApiClient\Promotion\Model\V0BidRecommendationReachMax',
        'reach_medium' => '\ValeryVerkhoturov\WbApiClient\Promotion\Model\V0BidRecommendationReachMedium',
        'reach_min' => '\ValeryVerkhoturov\WbApiClient\Promotion\Model\V0BidRecommendationReachMin'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'norm_query' => null,
        'reach_max' => null,
        'reach_medium' => null,
        'reach_min' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'norm_query' => false,
        'reach_max' => false,
        'reach_medium' => false,
        'reach_min' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'norm_query' => 'normQuery',
        'reach_max' => 'reachMax',
        'reach_medium' => 'reachMedium',
        'reach_min' => 'reachMin'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'norm_query' => 'setNormQuery',
        'reach_max' => 'setReachMax',
        'reach_medium' => 'setReachMedium',
        'reach_min' => 'setReachMin'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'norm_query' => 'getNormQuery',
        'reach_max' => 'getReachMax',
        'reach_medium' => 'getReachMedium',
        'reach_min' => 'getReachMin'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('norm_query', $data ?? [], null);
        $this->setIfExists('reach_max', $data ?? [], null);
        $this->setIfExists('reach_medium', $data ?? [], null);
        $this->setIfExists('reach_min', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets norm_query
     *
     * @return string|null
     */
    public function getNormQuery()
    {
        return $this->container['norm_query'];
    }

    /**
     * Sets norm_query
     *
     * @param string|null $norm_query Поисковый кластер
     *
     * @return self
     */
    public function setNormQuery($norm_query)
    {
        if (is_null($norm_query)) {
            throw new \InvalidArgumentException('non-nullable norm_query cannot be null');
        }
        $this->container['norm_query'] = $norm_query;

        return $this;
    }

    /**
     * Gets reach_max
     *
     * @return \ValeryVerkhoturov\WbApiClient\Promotion\Model\V0BidRecommendationReachMax|null
     */
    public function getReachMax()
    {
        return $this->container['reach_max'];
    }

    /**
     * Sets reach_max
     *
     * @param \ValeryVerkhoturov\WbApiClient\Promotion\Model\V0BidRecommendationReachMax|null $reach_max reach_max
     *
     * @return self
     */
    public function setReachMax($reach_max)
    {
        if (is_null($reach_max)) {
            throw new \InvalidArgumentException('non-nullable reach_max cannot be null');
        }
        $this->container['reach_max'] = $reach_max;

        return $this;
    }

    /**
     * Gets reach_medium
     *
     * @return \ValeryVerkhoturov\WbApiClient\Promotion\Model\V0BidRecommendationReachMedium|null
     */
    public function getReachMedium()
    {
        return $this->container['reach_medium'];
    }

    /**
     * Sets reach_medium
     *
     * @param \ValeryVerkhoturov\WbApiClient\Promotion\Model\V0BidRecommendationReachMedium|null $reach_medium reach_medium
     *
     * @return self
     */
    public function setReachMedium($reach_medium)
    {
        if (is_null($reach_medium)) {
            throw new \InvalidArgumentException('non-nullable reach_medium cannot be null');
        }
        $this->container['reach_medium'] = $reach_medium;

        return $this;
    }

    /**
     * Gets reach_min
     *
     * @return \ValeryVerkhoturov\WbApiClient\Promotion\Model\V0BidRecommendationReachMin|null
     */
    public function getReachMin()
    {
        return $this->container['reach_min'];
    }

    /**
     * Sets reach_min
     *
     * @param \ValeryVerkhoturov\WbApiClient\Promotion\Model\V0BidRecommendationReachMin|null $reach_min reach_min
     *
     * @return self
     */
    public function setReachMin($reach_min)
    {
        if (is_null($reach_min)) {
            throw new \InvalidArgumentException('non-nullable reach_min cannot be null');
        }
        $this->container['reach_min'] = $reach_min;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
