<?php

/**
 * GetUsersResponseUsersInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ValeryVerkhoturov\WbApiClient\General
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Общее
 *
 * В этом разделе: - [общая информация о WB API](https://dev.wildberries.ru/openapi/api-information#tag/introduction) - как [начать работу с WB API](https://dev.wildberries.ru/openapi/api-information#tag/introduction/Kak-nachat-rabotu-s-API) - как [авторизоваться](https://dev.wildberries.ru/openapi/api-information#tag/authorization) и [создавать токены](https://dev.wildberries.ru/openapi/api-information#tag/authorization/Kak-sozdat-personalnyj-bazovyj-ili-testovyj-token) - основные [статус-коды ответов](https://dev.wildberries.ru/openapi/api-information#tag/introduction/Status-kody-HTTP) - [лимиты запросов](https://dev.wildberries.ru/openapi/api-information#tag/introduction/Limity-zaprosov) - как обратиться в [поддержку](https://dev.wildberries.ru/openapi/api-information#tag/introduction/Podderzhka) С помощью методов этого раздела вы можете: - проверить [подключение к WB API](https://dev.wildberries.ru/openapi/api-information#tag/connectionCheck/operation/getPing) - получить [новости портала продавцов](https://dev.wildberries.ru/openapi/api-information#tag/newsApi/operation/getV2News) - получить [информацию о продавце](https://dev.wildberries.ru/openapi/api-information#tag/sellerInformation/operation/getV1SellerInfo) - [управлять пользователями продавца](https://dev.wildberries.ru/openapi/api-information#tag/sellerUserManagement)
 *
 * The version of the OpenAPI document: general
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ValeryVerkhoturov\WbApiClient\General\Model;

use ArrayAccess;
use ValeryVerkhoturov\WbApiClient\General\ObjectSerializer;

/**
 * GetUsersResponseUsersInner Class Doc Comment
 *
 * @category Class
 * @package  ValeryVerkhoturov\WbApiClient\General
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetUsersResponseUsersInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getUsersResponse_users_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'role' => 'string',
        'position' => 'string',
        'phone' => 'string',
        'email' => 'string',
        'is_owner' => 'bool',
        'first_name' => 'string',
        'second_name' => 'string',
        'patronymic' => 'string',
        'goods_return' => 'bool',
        'is_invitee' => 'bool',
        'invitee_info' => '\ValeryVerkhoturov\WbApiClient\General\Model\GetUsersResponseUsersInnerInviteeInfo',
        'access' => '\ValeryVerkhoturov\WbApiClient\General\Model\GetUsersResponseUsersInnerAccessInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'role' => null,
        'position' => null,
        'phone' => null,
        'email' => null,
        'is_owner' => null,
        'first_name' => null,
        'second_name' => null,
        'patronymic' => null,
        'goods_return' => null,
        'is_invitee' => null,
        'invitee_info' => null,
        'access' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'role' => false,
        'position' => false,
        'phone' => false,
        'email' => false,
        'is_owner' => false,
        'first_name' => false,
        'second_name' => false,
        'patronymic' => false,
        'goods_return' => false,
        'is_invitee' => false,
        'invitee_info' => true,
        'access' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'role' => 'role',
        'position' => 'position',
        'phone' => 'phone',
        'email' => 'email',
        'is_owner' => 'isOwner',
        'first_name' => 'firstName',
        'second_name' => 'secondName',
        'patronymic' => 'patronymic',
        'goods_return' => 'goodsReturn',
        'is_invitee' => 'isInvitee',
        'invitee_info' => 'inviteeInfo',
        'access' => 'access'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'role' => 'setRole',
        'position' => 'setPosition',
        'phone' => 'setPhone',
        'email' => 'setEmail',
        'is_owner' => 'setIsOwner',
        'first_name' => 'setFirstName',
        'second_name' => 'setSecondName',
        'patronymic' => 'setPatronymic',
        'goods_return' => 'setGoodsReturn',
        'is_invitee' => 'setIsInvitee',
        'invitee_info' => 'setInviteeInfo',
        'access' => 'setAccess'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'role' => 'getRole',
        'position' => 'getPosition',
        'phone' => 'getPhone',
        'email' => 'getEmail',
        'is_owner' => 'getIsOwner',
        'first_name' => 'getFirstName',
        'second_name' => 'getSecondName',
        'patronymic' => 'getPatronymic',
        'goods_return' => 'getGoodsReturn',
        'is_invitee' => 'getIsInvitee',
        'invitee_info' => 'getInviteeInfo',
        'access' => 'getAccess'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ROLE_USER = 'user';
    public const ROLE_EMPTY = '';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRoleAllowableValues()
    {
        return [
            self::ROLE_USER,
            self::ROLE_EMPTY,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('role', $data ?? [], null);
        $this->setIfExists('position', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('is_owner', $data ?? [], null);
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('second_name', $data ?? [], null);
        $this->setIfExists('patronymic', $data ?? [], null);
        $this->setIfExists('goods_return', $data ?? [], null);
        $this->setIfExists('is_invitee', $data ?? [], null);
        $this->setIfExists('invitee_info', $data ?? [], null);
        $this->setIfExists('access', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getRoleAllowableValues();
        if (!is_null($this->container['role']) && !in_array($this->container['role'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'role', must be one of '%s'",
                $this->container['role'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id ID пользователя
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets role
     *
     * @return string|null
     */
    public function getRole()
    {
        return $this->container['role'];
    }

    /**
     * Sets role
     *
     * @param string|null $role Роль пользователя:   * `user` — пользователь, который активировал доступ   * ` ` (пустая строка) — пользователь, который не активировал доступ
     *
     * @return self
     */
    public function setRole($role)
    {
        if (is_null($role)) {
            throw new \InvalidArgumentException('non-nullable role cannot be null');
        }
        $allowedValues = $this->getRoleAllowableValues();
        if (!in_array($role, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'role', must be one of '%s'",
                    $role,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['role'] = $role;

        return $this;
    }

    /**
     * Gets position
     *
     * @return string|null
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param string|null $position Должность пользователя
     *
     * @return self
     */
    public function setPosition($position)
    {
        if (is_null($position)) {
            throw new \InvalidArgumentException('non-nullable position cannot be null');
        }
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone Номер телефона пользователя
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Email пользователя
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets is_owner
     *
     * @return bool|null
     */
    public function getIsOwner()
    {
        return $this->container['is_owner'];
    }

    /**
     * Sets is_owner
     *
     * @param bool|null $is_owner Является ли пользователь владельцем профиля продавца
     *
     * @return self
     */
    public function setIsOwner($is_owner)
    {
        if (is_null($is_owner)) {
            throw new \InvalidArgumentException('non-nullable is_owner cannot be null');
        }
        $this->container['is_owner'] = $is_owner;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string|null $first_name Имя пользователя
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            throw new \InvalidArgumentException('non-nullable first_name cannot be null');
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets second_name
     *
     * @return string|null
     */
    public function getSecondName()
    {
        return $this->container['second_name'];
    }

    /**
     * Sets second_name
     *
     * @param string|null $second_name Фамилия пользователя
     *
     * @return self
     */
    public function setSecondName($second_name)
    {
        if (is_null($second_name)) {
            throw new \InvalidArgumentException('non-nullable second_name cannot be null');
        }
        $this->container['second_name'] = $second_name;

        return $this;
    }

    /**
     * Gets patronymic
     *
     * @return string|null
     */
    public function getPatronymic()
    {
        return $this->container['patronymic'];
    }

    /**
     * Sets patronymic
     *
     * @param string|null $patronymic Отчество пользователя
     *
     * @return self
     */
    public function setPatronymic($patronymic)
    {
        if (is_null($patronymic)) {
            throw new \InvalidArgumentException('non-nullable patronymic cannot be null');
        }
        $this->container['patronymic'] = $patronymic;

        return $this;
    }

    /**
     * Gets goods_return
     *
     * @return bool|null
     */
    public function getGoodsReturn()
    {
        return $this->container['goods_return'];
    }

    /**
     * Sets goods_return
     *
     * @param bool|null $goods_return Может ли пользователь одобрять возвраты товаров
     *
     * @return self
     */
    public function setGoodsReturn($goods_return)
    {
        if (is_null($goods_return)) {
            throw new \InvalidArgumentException('non-nullable goods_return cannot be null');
        }
        $this->container['goods_return'] = $goods_return;

        return $this;
    }

    /**
     * Gets is_invitee
     *
     * @return bool|null
     */
    public function getIsInvitee()
    {
        return $this->container['is_invitee'];
    }

    /**
     * Sets is_invitee
     *
     * @param bool|null $is_invitee Приглашён ли пользователь
     *
     * @return self
     */
    public function setIsInvitee($is_invitee)
    {
        if (is_null($is_invitee)) {
            throw new \InvalidArgumentException('non-nullable is_invitee cannot be null');
        }
        $this->container['is_invitee'] = $is_invitee;

        return $this;
    }

    /**
     * Gets invitee_info
     *
     * @return \ValeryVerkhoturov\WbApiClient\General\Model\GetUsersResponseUsersInnerInviteeInfo|null
     */
    public function getInviteeInfo()
    {
        return $this->container['invitee_info'];
    }

    /**
     * Sets invitee_info
     *
     * @param \ValeryVerkhoturov\WbApiClient\General\Model\GetUsersResponseUsersInnerInviteeInfo|null $invitee_info invitee_info
     *
     * @return self
     */
    public function setInviteeInfo($invitee_info)
    {
        if (is_null($invitee_info)) {
            array_push($this->openAPINullablesSetToNull, 'invitee_info');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invitee_info', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invitee_info'] = $invitee_info;

        return $this;
    }

    /**
     * Gets access
     *
     * @return \ValeryVerkhoturov\WbApiClient\General\Model\GetUsersResponseUsersInnerAccessInner[]|null
     */
    public function getAccess()
    {
        return $this->container['access'];
    }

    /**
     * Sets access
     *
     * @param \ValeryVerkhoturov\WbApiClient\General\Model\GetUsersResponseUsersInnerAccessInner[]|null $access Настройки доступа к разделам профиля продавца
     *
     * @return self
     */
    public function setAccess($access)
    {
        if (is_null($access)) {
            throw new \InvalidArgumentException('non-nullable access cannot be null');
        }
        $this->container['access'] = $access;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
