<?php

/**
 * PositionCluster
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ValeryVerkhoturov\WbApiClient\Analytics
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Аналитика и данные
 *
 * Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)
 *
 * The version of the OpenAPI document: analytics
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ValeryVerkhoturov\WbApiClient\Analytics\Model;

use ValeryVerkhoturov\WbApiClient\Analytics\ObjectSerializer;

/**
 * PositionCluster Class Doc Comment
 *
 * @category Class
 * @description Товары с какой средней позицией в поиске показывать в отчёте:   - &#x60;all&#x60; — все   - &#x60;firstHundred&#x60; — от 1 до 100   - &#x60;secondHundred&#x60; — от 101 до 200   - &#x60;below&#x60; — от 201 и ниже
 * @package  ValeryVerkhoturov\WbApiClient\Analytics
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PositionCluster
{
    /**
     * Possible values of this enum
     */
    public const ALL = 'all';

    public const FIRST_HUNDRED = 'firstHundred';

    public const SECOND_HUNDRED = 'secondHundred';

    public const BELOW = 'below';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ALL,
            self::FIRST_HUNDRED,
            self::SECOND_HUNDRED,
            self::BELOW
        ];
    }
}
