<?php

/**
 * StockType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ValeryVerkhoturov\WbApiClient\Analytics
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Аналитика и данные
 *
 * Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)
 *
 * The version of the OpenAPI document: analytics
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ValeryVerkhoturov\WbApiClient\Analytics\Model;

use ValeryVerkhoturov\WbApiClient\Analytics\ObjectSerializer;

/**
 * StockType Class Doc Comment
 *
 * @category Class
 * @description Тип складов хранения товаров:   - &#x60;\&quot;\&quot;&#x60; — все   - &#x60;wb&#x60; — склады WB   - &#x60;mp&#x60; — склады продавца
 * @package  ValeryVerkhoturov\WbApiClient\Analytics
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StockType
{
    /**
     * Possible values of this enum
     */
    public const EMPTY = '';

    public const WB = 'wb';

    public const MP = 'mp';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EMPTY,
            self::WB,
            self::MP
        ];
    }
}
