<?php

/**
 * ModelsHandySupplyStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ValeryVerkhoturov\WbApiClient\OrdersFbw
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Поставки FBW
 *
 * Узнать больше о поставках FBW можно в [справочном центре](https://seller.wildberries.ru/instructions/subcategory/5a8e1202-0865-45b7-acae-5d0afc7add56?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e)  В разделе описаны методы получения: - [информации для формирования поставок](https://dev.wildberries.ru/openapi/orders-fbw#tag/informationForFormingSupplies) - [информации о поставках](https://dev.wildberries.ru/openapi/orders-fbw#tag/suppliesInformation) Вы можете создавать карточки товара в песочнице [Контента](https://dev.wildberries.ru/openapi/api-information#tag/authorization/Kategorii-tokenov), а потом использовать баркоды товаров в [песочнице](https://dev.wildberries.ru/sandbox) Поставок
 *
 * The version of the OpenAPI document: ordersfbw
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ValeryVerkhoturov\WbApiClient\OrdersFbw\Model;

use ValeryVerkhoturov\WbApiClient\OrdersFbw\ObjectSerializer;

/**
 * ModelsHandySupplyStatus Class Doc Comment
 *
 * @category Class
 * @package  ValeryVerkhoturov\WbApiClient\OrdersFbw
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ModelsHandySupplyStatus
{
    /**
     * Possible values of this enum
     */
    public const NOT_PLANNED = 1;

    public const PLANNED = 2;

    public const ALLOW_UNLOAD = 3;

    public const ACCEPTING = 4;

    public const ACCEPTED = 5;

    public const VIRTUAL = 6;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_PLANNED,
            self::PLANNED,
            self::ALLOW_UNLOAD,
            self::ACCEPTING,
            self::ACCEPTED,
            self::VIRTUAL
        ];
    }
}
